[package]
name = "xml_schema_derive"
version = "0.0.1"
description = "Structure generator from XSD source file"
edition = "2018"

[lib]
name = "xml_schema_derive"
proc-macro = true

[dependencies]
log = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
Inflector = "0.11"
syn = { version = "1.0", features = ["visit", "extra-traits"] }
xml-rs = "0.8"
yaserde_derive = { version = "0.3" }
yaserde = { version = "0.3" }
